// <auto-generated />
using System;
using Infraestructura.Datos.Viaticos.UnidadDeTrabajo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructura.Datos.Viaticos.Migraciones
{
    [DbContext(typeof(ViaticosUnidadDeTrabajo))]
    [Migration("20221005191823_viaticos")]
    partial class viaticos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Viaticos.Entidades.FlujoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdNivelEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEnte")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioElimino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioModifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoFlujo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoEnte");

                    b.ToTable("Flujos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.NivelEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelEmpleados","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.PasoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaFirma")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFlujo")
                        .HasColumnType("int");

                    b.Property<int>("IdRolAutoriza")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioElimino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioModifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFlujo");

                    b.ToTable("Pasos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.TipoEntePublico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntePublicos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.FlujoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.TipoEntePublico", "EntePublico")
                        .WithMany()
                        .HasForeignKey("IdTipoEnte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.PasoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.FlujoViatico", "Flujo")
                        .WithMany("Pasos")
                        .HasForeignKey("IdFlujo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
