// <auto-generated />
using System;
using Infraestructura.Datos.Viaticos.UnidadDeTrabajo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructura.Datos.Viaticos.Migraciones
{
    [DbContext(typeof(ViaticosUnidadDeTrabajo))]
    partial class ViaticosUnidadDeTrabajoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Viaticos.Entidades.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFlujo")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioAutorizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioElimino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioModifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Sello")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autorizaciones","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.FlujoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdNivelEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEnte")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioElimino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioModifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoFlujo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoEnte");

                    b.ToTable("Flujos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.HistorialFlujoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdFlujo")
                        .HasColumnType("int");

                    b.Property<int?>("IdNivelEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEnte")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioModifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OperacionFin")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OperacionInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoFlujo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFlujo");

                    b.ToTable("HistorialesFlujos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.HistorialPasoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AplicaFirma")
                        .HasColumnType("bit");

                    b.Property<int>("IdFlujo")
                        .HasColumnType("int");

                    b.Property<int>("IdPaso")
                        .HasColumnType("int");

                    b.Property<int>("IdRolAutoriza")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioModifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OperacionFin")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OperacionInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPaso");

                    b.ToTable("HitorialesPasos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.NivelEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelEmpleados","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.PasoViatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaFirma")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFlujo")
                        .HasColumnType("int");

                    b.Property<int>("IdRolAutoriza")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioElimino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioModifico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFlujo");

                    b.ToTable("Pasos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.SolicitudCondensada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAfectacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAutorizacion")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioAutorizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioCreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SolicitudesCondensadas","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.TipoEntePublico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntePublicos","Viaticos");
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.FlujoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.TipoEntePublico", "EntePublico")
                        .WithMany()
                        .HasForeignKey("IdTipoEnte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.HistorialFlujoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.FlujoViatico", "FlujoViatico")
                        .WithMany("Historiales")
                        .HasForeignKey("IdFlujo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.HistorialPasoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.PasoViatico", "PasoViatico")
                        .WithMany("Historiales")
                        .HasForeignKey("IdPaso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Viaticos.Entidades.PasoViatico", b =>
                {
                    b.HasOne("Dominio.Viaticos.Entidades.FlujoViatico", "Flujo")
                        .WithMany("Pasos")
                        .HasForeignKey("IdFlujo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
